# Generated by Django 5.1.6 on 2025-03-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=41)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
