# Generated by Django 5.1.6 on 2025-03-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concession', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=41, unique=True)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
