# Generated by Django 5.1.6 on 2025-03-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concession', '0002_user_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='concession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'concession_user',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
