# Generated by Django 5.1.6 on 2025-03-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concession', '0003_concession_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcessionUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'concession_user',
            },
        ),
        migrations.DeleteModel(
            name='concession',
        ),
    ]
