# Generated by Django 5.1.6 on 2025-03-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concession', '0004_concessionuser_delete_concession'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignForm',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='ConcessionUser',
        ),
    ]
