# Generated by Django 5.1.6 on 2025-03-24 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concession', '0005_signform_delete_concessionuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('concession_id', models.AutoField(primary_key=True, serialize=False)),
                ('studentname', models.CharField(max_length=255)),
                ('collegename', models.CharField(max_length=255)),
                ('station1', models.CharField(max_length=100)),
                ('station2', models.CharField(max_length=100)),
                ('travel_class', models.CharField(max_length=50)),
                ('validity', models.IntegerField(choices=[(1, '1 Month'), (3, '3 Months')])),
                ('current_date', models.DateField()),
                ('valid_till_date', models.DateField()),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concession.signform')),
            ],
        ),
    ]
